name: choro_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - matplotlib
  - python-dotenv
  - pip:
    - Flask
    - Flask-WTF
    - gunicorn
    - Flask-Bootstrap5